#!/bin/bash

   echo '207' > Input.param
   cp OPENATI_POLICY_INPUT.0.B_ARNOLDI OPENATI_POLICY_INPUT.0
   cp OPENATI_POLICY_INPUT.1.B_ARNOLDI OPENATI_POLICY_INPUT.1
   cp OPENATI_POLICY_INPUT.2.B_ARNOLDI OPENATI_POLICY_INPUT.2
   cp OPENATI_POLICY_INPUT.3.B_ARNOLDI OPENATI_POLICY_INPUT.3


    export OMP_NUM_THREADS=4
    numactl -c 0 -i 0,1 ./lload
