#!/bin/bash

#!/bin/bash

    cp OPENATI_POLICY_INPUT.0.GMRES OPENATI_POLICY_INPUT.0
    cp OPENATI_POLICY_INPUT.1.GMRES OPENATI_POLICY_INPUT.1
    cp OPENATI_POLICY_INPUT.2.GMRES OPENATI_POLICY_INPUT.2
    cp OPENATI_POLICY_INPUT.3.GMRES OPENATI_POLICY_INPUT.3

    export OMP_NUM_THREADS=4
    numactl -c 0 -i 0 ./gload

    rm OPENATI_POLICY_INPUT.0
    rm OPENATI_POLICY_INPUT.1
    rm OPENATI_POLICY_INPUT.2
    rm OPENATI_POLICY_INPUT.3
